package ${packageName};

${importClasses}

/**
 * Generated by GServer, do not modify this file.
 **/
public interface ${className} {
	public ${entity} load(Object id);

	public void delete(${entity} entity);

	public void update(${entity} entity);

	public Object insert(${entity} entity);


}